### PR TITLE
Homework

### PR DESCRIPTION
**Pull request by arzatskis**
Tried to interpret homework assignment without knowing exactly whats expected exactly. Tried to show, that I understand various concepts of frontend development. Don't have much experience with React, so just rolled with knowledge I have without much googling. Intentionally aimed for simple React app/components without much dependencies etc.

Tried to separate "initial" screen so app looks good, while everything is loading etc.

- App based on `create-react-app`, so needed to add few custom scripts
- Didn't follow design mockup pixel to pixel. Kept everything with sane `rem` units. (Also used Affinity Designer for opening .psd, not sure if everything was displayed correctly)
- Tried to leave comments to show my thinking
- You emphasised, that you love structure. Not entirely sure what this means. Didn't thought about this much, picked "old school" approach and started coding. Separated `app` and `lib` components, so we could run linters only on "our" code etc. Personally would like to try keeping all component related files in single dir, but somehow imports may look to verbose..

Spent third of the entire time spent hunting Bootstrap's variables and checking behaviour.

**Todo:**
- [x] Load servers list
- [x] Logout icon/placement
- [x] Add Roboto as app font
- [x] Check font sizes
- [x] Split login form component and it's concerns
- [x] Spec samples
- [x] ~~Test/fix IE11~~
- [x] Logout
- [x] Proper routing with permissions
- [x] Remove hardcoded token 😀

There are some places that I still don't like (e.g. css is spit randomly by source file), but not sure if I need to hunt down all such issues. Assuming homework is for checking how I approach things, not to have perfect login app.

### CODE REVIEW

**Comment by arzatskis** [comment]
@tmxyz since we haven't spoke before about this assignment, could you outline, where I should focus most? Feeling that this can be improved infinitely, yet don't want to spend too much time on this.

**Comment by tmxyz** [comment]
Hi @arzatskis I will check what you have done and let you know if something needs to be improved. I see that you have listed several todos in the description, are those completed right now?

**Comment by arzatskis** [comment]
@tmxyz will try to keep list updated, so unchecked items are yet to be done. Just wanted to double check and ask, where should I put most emphasis, as I feel that this can be polished for days.. 😄

**Comment by tmxyz** [comment]
Before I can start the review you must finish what you have in your todo, most of the items there are essential. You don't need to be pixel perfect right now, but it has to be close enough :) In addition to that I would like to see some unit tests. When you have that ping me and I'll review the code :)

**Comment by arzatskis** [comment]
Finally got some time for specs - added few for different type of components. Hope you guys can check code now, meanwhile I'll try to setup virtual machine with IE on my home compute..

**Comment by arzatskis** [comment]
Haven't worked with ES6 codebase before, usually maintained older projects and it shows - different styles are mixed in this PR. Not overthinking this, not sure it's worth changing everything now etc. I'm aware of this issue. Like I've said before - didn't try to perfect everything, just want to show that I'm able to navigate and build stuff.

**Comment by arzatskis** [comment]
ping @tmxyz @mindaugas-jacionis

**Comment by tmxyz** [comment]
@arzatskis ready for review? If yes, remove WIP.

**Comment by Mindaugas-Jacionis** [comment]
Hi! We have reviewed your app, as a first time using React.js it is pretty good, congratz! :) 
Here is some comments that came out of the review:

Feedback
- Unsorted (sort util is made for alphabetical sorting, but trying to sort numerical)
- On slow internet surfer background `img` flashes, this makes it look a bit glitchy
- Critical css has background `img` which adds load time and "weight" to all pages - would be better to use solid color as critical property(blue on login and white on other pages)
- Components dir seems rather chaotic, would be nice to have structure there(just split them into dirs based on either they are general or screen specific components)
- Exit icon could have been general use component `<Icon>` that simply accepts prop defining which `svg` to use for icon
- Tests for utils would be nice too(this probably would have helped to see numeric sorting issue)
- `App.js` should sit in top level js dir(javascripts) as it is your app entry point(not so much of a general/screen specific component)
- `NavigationBrand` - unnecessary component as it is just a wrapper around `Logo` component, could have used `Logo` and wrapped it or add wrapper(maybe conditional one) inside render of `Logo`
- `ServersList` component is simply rendering `DetailedList` component(nothing else), so why not call this component directly, now basically you are duplicating a Component.

Requests
- Could you rewrite few functional components as ES6 arrow functions? What is the reasoning you chose to use named functions over arrow functions?
- Could you add `PropType` validation & defaults to at least few components?
- Could you use destructuring in some component to destruct props?
- Could you add at least one snapshot test that also checks for some props/classes or validates interaction(i.e.: button click)?

Discussion/Questions:
- Since your component is named `Navigation` - maybe it would make sense to use `<nav>` html tag instead of `<header>`(most likely nav will be part of the `header`, or can be used in other parts of page - maybe `nav` in `footer` as well in other pages), what do you think?
- Why you chose `<section>` as a Page wrapper? `<section>` is used to define part of the page(specific section, usually one of multiple ones)? Maybe it would make more sense to have `<main>` or simply `<div>` as a wrapper? This decision has some effect on SEO as well as page crawlers are looking at semantics of the page.
- Is there any particular reason for using different measurement units in `css`? It seems rather chaotic - common practice would be to stick to one specific unit(`px`, `em` and etc.) unless there is some gains from using other.

**Comment by arzatskis** [comment]
> Unsorted (sort util is made for alphabetical sorting, but trying to sort numerical)

Ok, will update this. Assumed this was more for checking where I'd place function etc. and didn't get to  CS stuff 

> On slow internet surfer background img flashes, this makes it look a bit glitchy
> Critical css has background img which adds load time and "weight" to all pages - would be better to use solid color as critical property(blue on login and white on other pages)

I tried to comment on this, that I'm not exactly sure what todo with that background image. Personally, I'd probably treat it as enhancement and load it separately together with lazy loaded app code and then orchestrate animation, so background and form animates in when everything is ready

> Components dir seems rather chaotic, would be nice to have structure there(just split them into dirs based on either they are general or screen specific components)

Agree that it's messy and would not be very usable with "real" app with a lot more components

> Exit icon could have been general use component <Icon> that simply accepts prop defining which svg to use for icon

Totally agree, bit since only one icon is used across the app I just rolled with this (I try to follow "make it work -> make it good -> make it fast" approach). I though about this from the start, but decided to avoid digging how to make it dynamically. Questions like *"should all icons svg code be inlined? what about unused icons then"* etc. I'm confident there's webpack plugins to handle all this, but since I avoided ejecting default crate-react-app config and dealing with plugins to inline svg, avoided this same work for icons too. 

> Tests for utils would be nice too(this probably would have helped to see numeric sorting issue)

Didn't want to test everything, just illustrate few different components specs. Agree that this would have shown issues with my sorting.

> App.js should sit in top level js dir(javascripts) as it is your app entry point(not so much of a general/screen specific component)

Was thinking to rename `index.js` to `app.js`, but `create-react-app` looks for such file specifically - I'd assume this file is "entry point". Having more sub-directories for components would solve this IMHO - e.g. App.js (component) could live in root dir of components, where smaller ones are sorted in sub-dirs.

> NavigationBrand - unnecessary component as it is just a wrapper around Logo component, could have used Logo and wrapped it or add wrapper(maybe conditional one) inside render of Logo

I think my original thinking was that we could have screen-hidden text for brand name etc. to show for screen readers etc., just didn't came back to solve such cases

> ServersList component is simply rendering DetailedList component(nothing else), so why not call this component directly, now basically you are duplicating a Component.

In it's current form it totally makes sense. Didn't handle cases for cases when list is empty etc. - we would probably need more components, this is why I started with standalone file. Should have left more comments at least

**Comment by arzatskis** [comment]
> Since your component is named Navigation - maybe it would make sense to use <nav> html tag instead of <header>(most likely nav will be part of the header, or can be used in other parts of page - maybe nav in footer as well in other pages), what do you think?

Bootstrap stuff took me longest, didn't thought much about this. Just copied structure directly from getbootstrap.com page source code. Turns out they're using `header`. I agree that maybe it's not best tag for navigation html, but also think that `Navigation.js` component should be coupled with CSS class name, not element itself - it's one of the reasons why we use class names for defining styles: we don't need to worry which element as html tag. 

> Why you chose <section> as a Page wrapper? <section> is used to define part of the page(specific section, usually one of multiple ones)? Maybe it would make more sense to have <main> or simply <div> as a wrapper? This decision has some effect on SEO as well as page crawlers are looking at semantics of the page.

I think I was following my thoughts and how I would write this. "Login section", "Content section" at leasts *sounds* logically for me this is why i rolled with this. I also imagined these as app "sections" (ala iOS app tabs). So reasons are purely grammatical - didn't though about SEO at all doing this. It's nice that you guys care about such things - would definitely consider this working public sites. It this case - content is hidden and crawlers can't login to app.

> Is there any particular reason for using different measurement units in css? It seems rather chaotic - common practice would be to stick to one specific unit(px, em and etc.) unless there is some gains from using other.

I agree this may be/look chaotic and probably some `px` values could be replaced with more common `rem`. Yet sometimes it depends on how you want your design to behave. Properties like `border-radius` / `box-shadow` could scale with root units, but somehow feels that they are more or less "fixed". The same with `border-width` property or icons size, or adjusting margin/offset so font x-height issues - "it depends™" 😆. 

Sometimes it's pure developer ergonomics if you want your border to be 1px (always) why bother with calculating it with `rem` values - you won't know how it behaves and what's get calculated in final view. This may lead to  blurriness, too big or too small values, where screens (especially non retina) may totally ignore. You could always "reset" your root element font size, so `1rem` always equals `10px`, but I believe it somehow destroys all the elegance of being able to tweak this one value and have your UI scaled up/down.

**Comment by arzatskis** [comment]
Thanks for comments @tmxyz, will finish up with requested changes tomorrow

**Comment by arzatskis** [comment]
@Mindaugas-Jacionis updated `<Button />` component with requested features demonstrated.

As for inconsistencies with ES5/ES6/arrows/etc. - as I've said before, before starting this task I had little experience with ES6, so just went with what I know. The more I worked on this the more familiar new concept became and I felt more comfortable using them. Not sure it's worth updated everything now. Having work machine and proper dev-env setup, style guide to follow, linters, prettier etc. would solve these problems

**Pull request merged**
